version: "3.9"

services:
  db:
    image: mysql:8.0
    container_name: todo-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: todo_db
      MYSQL_USER: todo_user
      MYSQL_PASSWORD: todo_pass
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5

  backend:
    build: ./backend
    container_name: todo-backend
    restart: always
    depends_on:
      db:
        condition: service_healthy
    environment:
      DATABASE_HOST: db
      DATABASE_USER: todo_user
      DATABASE_PASSWORD: todo_pass
      DATABASE_NAME: todo_db
    ports:
      - "5000:5000"

  frontend:
    build: ./frontend
    container_name: todo-frontend
    restart: always
    stdin_open: true
    tty: true
    depends_on:
      - backend
    ports:
      - "3000:3000"

volumes:
  db_data:
